const ErrorCodes = {
  INVALID_KEY: "CL01",
  CLIENT_OFFLINE: "CL02",
  SERVER_ERROR_CHECK_IF_EXISTS: "SR03",
  SERVER_ERROR_AUTO_ADD: "SR04",
  SERVER_ERROR_FETCH: "SR05",
  UNKONWN_ERROR: "UN06",
};

export default ErrorCodes;
