org: kjsudi
app: aws-cron-insert-latest-quote-sg-ce
service: aws-cron-insert-latest-quote-sg-ce

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every day at 8:15AM
      - schedule: cron(15 8 * * ? *)
